site_name: ZP's docs
site_url: https://zp1008611.github.io/
site_description: the notes record by ZhongPei

nav:
    - Home: index.md
    
    - 运筹与优化:
        - 精确式算法: 
            - OROPT/or_exact/index.md
            - Optimality Conditions: OROPT/or_exact/optimality_conditions/README.md
            - Dual Theory: OROPT/or_exact/dual_theory/README.md
            - LP Introduction: OROPT/or_exact/LP_intro/README.md
            - LP Simplex Method: OROPT/or_exact/LP_simplex/README.md
            - LP Interior Point Method: OROPT/or_exact/LP_interior/README.md
            - Column Generation for LP: OROPT/or_exact/LP_cg/README.md
            - Dantzig-Wolfe Decomposition for LP: OROPT/or_exact/LP_dw_decompostition/README.md
            - Integer Programming: OROPT/or_exact/IP_intro/README.md
            - Convex Hull and Valid Inequalities: OROPT/or_exact/IP_convex_hull_and_valid_ineq/README.md
            - Branch and Bound: OROPT/or_exact/IP_branch_and_bound/README.md
            - Relaxation: OROPT/or_exact/IP_relaxation/README.md
            - Cutting Planes: OROPT/or_exact/IP_cutting_planes/README.md
            - Branch and Cut: OROPT/or_exact/IP_branch_and_cut/README.md
            - Row and column generation for large-scale models: OROPT/or_exact/LP_large_scale_models/README.md
            - Dantzig-Wolfe Decomposition for IP: OROPT/or_exact/IP_dw_decomposition/README.md
            - Branch and Price: OROPT/or_exact/IP_branch_and_price/README.md
            - Benders Decomposition for IP: OROPT/or_exact/IP_beaders_decomposition/README.md
        - 元启发式算法:
            - OROPT/or_metaheuristics/index.md
            - ALNS: OROPT/or_metaheuristics/ANLNS/README.md
        - Project:Cutting stock problem:
            - OROPT/or_project_cutting_stock_problem/index.md
        - Project:2DRP:
            - OROPT/or_project_2DRP/index.md
        - Project:3DBP:
            - OROPT/or_project_3DBP/index.md
        - Project:VRP:
            - OROPT/or_project_vrp/index.md
            - CVRP: OROPT/or_project_vrp/CVRP/README.md
        - Project:FJSP:
            - OROPT/or_project_FJSP/index.md
        
    - ML:
        - Supervised Learning:
            - ML/supervised_learning/index.md
            - Tree: ML/supervised_learning/tree/README.md


    - DL: 
        - DL/index.md
        - Multilayer Perceptrons: DL/Basics/MLPs/README.md
        - Sigmoid Neurons: DL/Basics/sigmoid_nn/README.md
        - Feedforward Neural Networks and Backpropagation: DL/Basics/FNN/README.md
        - NN Optimizer: DL/Basics/nn_optimizer/README.md
        - Regularization: DL/Basics/Regularization/README.md
        - Neural Network Training Tips: DL/Basics/nn_training_tips/README.md
        - Batch Normalization 详解: DL/Basics/BN/README.md
        - CNN: DL/Basics/CNN/README.md
        - RNN: DL/Basics/RNN/README.md
        - LSTM and GRU: DL/Basics/LSTM_GRU/README.md
        - 关于激活函数: DL/Basics/Activation_Function/README.md
        - Encoder Decoder models and Attention: DL/Basics/ENCODER_DECODER_Attention/README.md
        - Transformer: DL/Basics/Transformer/README.md
        - GNN:
            - DL/GNN/index.md
        - Paper Reading:
            - DL/READING/index.md
        - Project:NLP:
            - DL/dl_project_nlp/index.md
            - NNLM: DL/dl_project_nlp/NNLM/README.md
        - Project:Forecasting:
            - DL/dl_project_forecasting/index.md
        - Project:Customer&Marketing:
            - DL/dl_project_customer_marketing/index.md



    - RL:
        - RL/index.md
        - MDPs: RL/MDPs/README.md
        - BBO: RL/BBO/README.md
        - Bellman Equation: RL/Bellman_eq
        - Policy Iteration and Value Iteration: RL/PI_and_VI/README.md
        - Monte Carlo Methods: RL/MCM/README.md
        - TD Learning:Sarsa, Q-learning: RL/TD_Sarsa_Qlearning/README.md
        - Policy Gradient:REINFORCE: RL/PG_REINFORCE/README.md
        - Project:Order Dispatching:
            - RL/rl_project_order_dispatching/index.md
        - Project:Pricing Optimization: 
            - RL/rl_project_pricing_opt/index.md

    # - LLMs:
    #     - LLMs/index.md
    #     - 效率优化:
    #         - LLMs/efficiency_optimization/


    - LEETCODE:
        - LEETCODE/index.md
        - 动态规划:
            - LEETCODE/dp/README.md
        - DFS和BFS:
            - LEETCODE/dfs_bfs/README.md
        - 最短路:
            - LEETCODE/shortest_path/README.md
        - 二叉树:
            - LEETCODE/binary_tree/README.md
        - 回溯:
            - LEETCODE/backtrack/README.md
        - 滑动窗口:
            - LEETCODE/sliding_window/README.md
        - 双指针:
            - LEETCODE/double_pointer/README.md
        - 二分算法:
            - LEETCODE/binary_search_algorithm/README.md
        - 链表:
            - LEETCODE/linked_list/README.md
        - 单调栈与单调队列:
            - LEETCODE/monotonic_stack/README.md
        - 常用数据结构:
            - LEETCODE/data_structure/README.md
        - 位运算:
            - LEETCODE/bit_operation/README.md
        - 计算几何:
            - LEETCODE/computational_geometry/README.md
        - 刷题思路记录:
            - LEETCODE/thought_record/README.md
        - HOT100快速复习:
            - LEETCODE/hot100/README.md
        - 机考实战:
            - LEETCODE/comupter_testing/README.md   
    
    - 大模型技术学习:
        - LLMs_RECORDS/index.md
        - Agentic-RL:
            - LLMs_RECORDS/Agentic-RL/index.md
            - 绪论: LLMs_RECORDS/Agentic-RL/agent-rl-motivation/README.md
            - Search-R1: LLMs_RECORDS/Agentic-RL/agentic-rl-search-r1/README.md
            - AgentFlow: LLMs_RECORDS/Agentic-RL/agentic-rl-agentflow/README.md
        


    # - Math:
    #     - MATH/index.md
    #     - 图论:
    #         - MATH/Graph_theory/index.md

    # - 高中数学教资面试:
    #     - Teaching_Interview/index.md
    #     - 试讲真题练习: 
    #         - Teaching_Interview/Real_Questions/index.md
    #         - 三角函数: Teaching_Interview/Real_Questions/Textbook_Trial_Compulsory1_ch5
    #     - 结构化:
    #         - Teaching_Interview/Structuring/README.md

edit_uri: edit/main/docs
docs_dir: docs/

#[UI]
theme:
  name: material
  language: zh # 一些提示性的文字会变成中文
  # custom_dir: docs/overrides/
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.tabs
    - navigation.prune
    - navigation.footer
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    # - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - content.code.copy
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      toggle:
        icon: material/brightness-7  # 图标
        name: Switch to dark mode
      primary: deep ## 上方的, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: deep # # 链接等可交互元件的高亮色 [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: deep #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: deep # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  icon: 
    repo: fontawesome/brands/github #右上角图标
repo_name: zp1008611 # 右上角的名
repo_url: https://github.com/zp1008611 # 右上角点击跳转的链接




extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.18/katex.min.css
  #   - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  #   - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - stylesheets/extra.css
  #   - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # 网站统计
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
#   - javascripts/loadMermaid.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - statistics
  #   - mermaid2:
  #       version: 10.2.0
  #       arguments:
  #         securityLevel: "loose"
  - search:
      separator: '[\s\u200b\-]'
      lang: zh
  - git-authors:
      show_contribution: true
      exclude:
        - index.md
      enabled: true
  - git-revision-date-localized:
      type: datetime
      custom_format: "%d %B %Y"
      timezone: Asia/Shanghai
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
        - index.md
      enabled: true

markdown_extensions:
  - admonition
  - abbr
  - pymdownx.caret    
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      title: On this page
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - tables
     
# google_analytics:
#   - G-DZ1S490E8S
#   - auto

# extra:
#   social:
    # - icon: fontawesome/brands/github
#       link: https://github.com/SmilingWayne
#     - icon: fontawesome/brands/instagram
#       link: https://www.instagram.com/smilingwayne/
#     - icon: fontawesome/solid/paper-plane
#       link: mailto:xiaoxiaowayne@163.com
#   analytics:
#     provider: google
#     rpoperty: G-NVXC1ZHJ8C
#     feedback:
#       title: Was this page helpful?
#       ratings:
#         - icon: material/emoticon-happy-outline
#           name: This page was helpful
#           data: 1
#           note: >-
#             Thanks for your feedback!
#         - icon: material/emoticon-sad-outline
#           name: This page could be improved
#           data: 0
#           note: >-
#             Thanks for your feedback! Help us improve this page by
#             using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

copyright: Copyright &copy; 2025 ZhongPei 