site_name: ZP's docs
site_url: https://zp1008611.github.io/
site_description: the notes record by ZhongPei

nav:
  - 运筹与优化:
    - 精确式算法:
        - 最优性条件: oropt/or_exact/optimality_conditions/README.md


edit_uri: edit/main/docs
docs_dir: docs/
theme:
  language: "zh"
  name: material
  custom_dir: docs/overrides/
  font: false
  logo: images/Favicon.png
  #     text: Noto Serif SC
  #   custom_dir: /docs/stylesheets/
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.sections
    # - navigation.expand
    - navigation.top
    - navigation.indexes
    # - content.action.edit
    # - content.action.view

  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    annotation: material/arrow-right-circle

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.18/katex.min.css
  #   - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  #   - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - stylesheets/extra.css
  #   - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/extra.js
  - javascripts/mathjax.js
#   - javascripts/loadMermaid.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - statistics
  #   - mermaid2:
  #       version: 10.2.0
  #       arguments:
  #         securityLevel: "loose"
  - tags:
      tags_file: Website/tags.md
  - search:
      separator: '[\s\u200b\-]'
      lang: zh
  - git-authors:
      show_contribution: true
      exclude:
        - index.md
      enabled: true
  - git-revision-date-localized:
      type: datetime
      custom_format: "%d %B %Y"
      timezone: Asia/Shanghai
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
        - index.md
      enabled: true

#   - blogging:
#       dirs: # The directories to be included
#         - Arts
#   - rss:
#       match_path: Study/.*
#       date_from_meta:
#         as_creation: date
#       categories:
#         - categories
#         - tags

markdown_extensions:
  - admonition
  - meta
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets


  - pymdownx.arithmatex:
      generic: true
      block_tag: "pre"
  - toc:
      permalink: ⚓︎
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SmilingWayne
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/smilingwayne/
    - icon: fontawesome/solid/paper-plane
      link: mailto:xiaoxiaowayne@163.com
  analytics:
    provider: google
    rpoperty: G-NVXC1ZHJ8C
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

copyright: Copyright &copy; 2025 ZhongPei 